In [2]:
import torch
from torch.autograd import Variable
import numpy as np
#import tensorflow as tf

np.random.seed(0)

http://cs231n.stanford.edu/slides/2017/cs231n_2017_lecture8.pdf

In [3]:
N, D = 3,4

x = np.random.randn(N, D)
y = np.random.randn(N, D)
z = np.random.randn(N, D)

### Numpy

In [4]:
a = x * y
b = a + z
c = np.sum(b)

In [5]:
grad_c = 1.0
grad_b = grad_c * np.ones((N, D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_x = grad_a * y
grad_y = grad_a * x

In [6]:
print(grad_x)
print(grad_y)
print(grad_z)

[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Tensorflow

In [ ]:
x_ = tf.placeholder(tf.float32)
y_ = tf.placeholder(tf.float32)
z_ = tf.placeholder(tf.float32)

a = x_ * y_
b = a + z_
c = tf.reduce_sum(b)

In [ ]:
grad_x, grad_y, grad_z = tf.gradients(c,[x_,y_,z_]) # ∂c/∂x ...

with tf.Session() as sess:
    values = {
        x_ : x,
        y_ : y,
        z_ : z,
    }
    out = sess.run([c,grad_x,grad_y,grad_z],feed_dict=values)
    
    c_val, grad_x_val, grad_y_val, grad_z_val = out
    
print(grad_x_val)
print(grad_y_val)
print(grad_z_val)

### Pytorch

In [10]:
x_ = Variable(torch.from_numpy(x),requires_grad=True)
y_ = Variable(torch.from_numpy(y),requires_grad=True)
z_ = Variable(torch.from_numpy(z),requires_grad=True)

a = x_ * y_
b = a + z_
c = torch.sum(b)

In [11]:
c.backward()

print(x_.grad.data.numpy())
print(y_.grad.data.numpy())
print(z_.grad.data.numpy())

[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
