In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import numpy as np

torch.manual_seed(1)

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### 1. x와 y를 더한 값을 z와 element-wise하게 곱하기

In [2]:
x = [1., 2., 1.]
y = [2., 1., 2.]
z = [2., 2., 2.]

In [4]:
torch.mul(torch.Tensor(x) + torch.Tensor(y), torch.Tensor(z))

tensor([6., 6., 6.])

### 2. x와 y를 내적하시오

In [5]:
x = [1.,2.,1.]
y = [2.,1.,2.]

torch.dot(torch.Tensor(x), torch.Tensor(y))

tensor(6.)

### 3. 벡터 x와 벡터 y를 concat하고 벡터 z와 더하시오

In [6]:
x = [1.,2.,3.]
y = [3.,2.,1.]
z = [1.,1.,1.,1.,1.,1.]

torch.cat([torch.Tensor(x), torch.Tensor(y)]).add(torch.Tensor(z))

tensor([2., 3., 4., 4., 3., 2.])

### 4. $XW^T+b$ 를 구하시오

In [33]:
X = [[1.,2.],[3.,4.],[5.,6.]] # 3x2
W = [[0.1,1.2,0.5,0.3,0.2,0.1],[0.02,0.3,1.5,-0.2,0.0,1.6]] #2x6
b = torch.ones(2)

X = torch.Tensor(X)
W = torch.Tensor(W)
b = torch.Tensor(b)

torch.matmul(X.view(1, -1), W.transpose(0, 1)) + b.view(1, -1)

tensor([[ 7.8000, 14.9200]])

### 5. Model의 파라미터를 다 0으로 바꾸시오

In [37]:
class NN(nn.Module):
    def __init__(self):
        super(NN,self).__init__()
        self.l1 = nn.Linear(10,10)
        self.l2 = nn.Linear(10,2)
    
    def forward(self,inputs):
        outputs = F.relu(self.l1(inputs))
        return self.l2(outputs)

In [38]:
model = NN()

In [44]:
for param in model.parameters():
    p`aram.data = torch.zeros(param.data.size())

In [46]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
Parameter containing:
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)
